### ISSUE TITLE
There is a white point in the center of screen while playing.

### ISSUE THREAD

**Issue by A-Circle-Zhang** [DIYgod/DPlayer#101]
There is a white point in the center of screen while playing, and it's flashing...
播放的时候有个白点闪，暂停就没了。影响范围很广，几乎不是最新版本的 Chrome 内核浏览器都会收影响。

![Picture](https://user-images.githubusercontent.com/11173242/27779916-5b7e952c-5ff8-11e7-9b3d-28b7af43f3f0.png)

- The steps to reproduce.
**Play.**
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
**dplayer.js.org**
- Which versions of DPlayer, and which browser / OS are affected by this issue?
**Chrome 50 ( Chrome / 360 / Liebao, etc )**

**Comment by DIYgod** [comment]
Fixed. https://github.com/DIYgod/DPlayer/commit/07ef15b20aac554f7353d911838ec23e42c86907
