### ISSUE TITLE
你好，我们真的很希望DPlayer播放器里面要是可以增加视频画面质量定义清晰度这个功能就完美了

### ISSUE THREAD

**Issue by nba4488** [DIYgod/DPlayer#103]
你好，我们真的很希望DPlayer播放器里面要是可以增加视频画面质量定义清晰度这个功能就完美了，我们真的觉得DPlayer播放器里面的是视频画面质量定义清晰度唯一的缺陷问题情况，要是可以解决这个问题情况就完美了，这个是我们给DPlayer播放器的建议和意见还有反馈情况好吗
![1d8a5334305b7faf52b68d7c1368353b](https://user-images.githubusercontent.com/29298373/28304906-4cfa9aac-6bcc-11e7-93ed-3bec63245280.png)
![12faaab1fd558517dc08d5abcabadc0d](https://user-images.githubusercontent.com/29298373/28304909-511de79c-6bcc-11e7-8725-7c35c040de2f.png)

**Comment by DIYgod** [comment]
Go to read Docs.

**Comment by liwanglin12** [comment]
OR pay ￥500 for this question and contact @DIYgod 。

**Comment by fly3949** [comment]
@liwanglin12 Pay  ￥233 to me is OK, too .

**Comment by liwanglin12** [comment]
@fly3949 Or pay me ￥166. Than the above two are concessions.

**Comment by dixyes** [comment]
来解释一下 作者设计的dplayer本为毕设之后开源

作为h5弹幕播放器 本着keep it simple and stupid的原则，仅增添了部分必要的 ~~ 和一点都不simple stupid的 ~~ 功能

因此这类功能请自己实现，也可以实现之后提交pr（不一定merge

**Comment by fly3949** [comment]
@dixyes 实际上本来就是支持的...

**Comment by DIYgod** [comment]
@dixyes 这个已经实现了，文档里有写

**Comment by liwanglin12** [comment]
@dixyes 所以这个issue的问题其实是不看文档就来乱发issue的典型案例……语气还不是太好：
“这个是我们给DPlayer播放器的建议和意见还有反馈情况好吗 ” 
DIYgod：不好，滚（雾

**Comment by dixyes** [comment]
[doc里的介绍](http://dplayer.js.org/docs/#/?id=quality-switching)
