### ISSUE TITLE
手机上播放时一直有一个暂停按钮。There is always a pause button when playing on mobile

### ISSUE THREAD

**Issue by easychen** [DIYgod/DPlayer#1035]
重现步骤：

1. 打开官网，用 devtools 切换到手机模拟器状态
2. 刷新，然后点击播放（注意要刷新，不然不会出现）
3. 可以看到暂停图标一直出现

更简单的复现方式：

1. 用手机chrome打开官网
2. 点击播放

Steps to reproduce:

1. Open the official website and use devtools to switch to the mobile phone simulator state
2. Refresh, and then click play (pay attention to refresh, otherwise it will not appear)
3. You can see the pause icon keeps appearing

A simpler way to reproduce:

1. Open the official website with mobile chrome
2. Click to play

![image](https://user-images.githubusercontent.com/1294760/93204079-0c2b5200-f788-11ea-8985-7e8a27d66afa.png)

**Comment by a1010841065** [comment]
个人看来这似乎不是一个bug，反而更像是一个为移动设备专门做的触摸优化。点击按钮可以播放或暂停，点空白位置就会隐藏那个大的暂停按钮和进度条。但是我觉得这个功能还有继续优化的空间，比如2到3秒之后自动隐藏那个暂停按钮和进度条，这样看起来就会很舒服。

**Comment by yudewei** [comment]
看源码发现 移动端没有设置 自动隐藏setAutoHide的方法 
可以通过曲线救国方法实现
dplayer.container.addEventListener('mousemove', () => {
        dplayer.controller.setAutoHide()
      })
      dplayer.container.addEventListener('click', () => {
        dplayer.controller.setAutoHide()
      })

**Comment by hklcf** [comment]
> 看源码发现 移动端没有设置 自动隐藏setAutoHide的方法
> 可以通过曲线救国方法实现
> dplayer.container.addEventListener('mousemove', () => {
> dplayer.controller.setAutoHide()
> })
> dplayer.container.addEventListener('click', () => {
> dplayer.controller.setAutoHide()
> })

mousemove應該不需要

**Comment by kingsfeng** [comment]
根据楼上的小伙伴提供的方法改良了一下！
代码如下，监听播放状态，点击播放的时候加上自动隐藏方法。
dp.on('playing', function () {
      console.log('playing')
      dp.controller.setAutoHide()
      hideErrorBox()
    })
