### ISSUE TITLE
DPlayer播放器视频画面质量定义清晰度里面要是可以增加1080P和4K还有原画视频观看

### ISSUE THREAD

**Issue by nba4488** [DIYgod/DPlayer#105]
你好，我们真的很希望DPlayer播放器视频画面质量定义清晰度里面要是可以增加1080P和4K还有原画视频画面质量定义清晰度观看视频就很完美了

**Comment by nba4488** [comment]
![1d8a5334305b7faf52b68d7c1368353b](https://user-images.githubusercontent.com/29298373/28323671-0f60f764-6c0c-11e7-9d29-997da5ec9f8d.png)

**Comment by nba4488** [comment]
![1d8a5334305b7faf52b68d7c1368353b](https://user-images.githubusercontent.com/29298373/28323718-32adac08-6c0c-11e7-90af-e4d773596c46.png)
![12faaab1fd558517dc08d5abcabadc0d](https://user-images.githubusercontent.com/29298373/28323732-35a26c28-6c0c-11e7-88ba-54d74838b490.png)

**Comment by liwanglin12** [comment]
@DIYgod 建议把这个人拉黑，并邮件通知 Github 这个用户恶意发 Issue 的行为

**Comment by wjm2038** [comment]
围观智障

**Comment by dixyes** [comment]
翻译一下：设置option.video.quality而不是option.video.url

例如

    var dp = new DPlayer({
        // ...
        video: {
            quality: [{
                name: '114514p',
                url: '甚高清.mp4'
            }, {
                name: '12450p',
                url: '极超清.mp4'
            }],
            defaultQuality: 0,
            // ...
        }
    });

**Comment by liwanglin12** [comment]
@dixyes 其实不太希望就这样满足伸手党了

**Comment by RexSkz** [comment]
智。。智障？😂

**Comment by dixyes** [comment]
@liwanglin12 一个是要用爱感化zz 不要让他们走上更加邪恶的道路

另一个英文文档对dplayer的相当多的汉语母语的使用者并不友好

**Comment by liwanglin12** [comment]
@dixyes 就不能 Google Translation 一下…… 表示实在无法理解别人都已经让他看文档了还熟视无睹的再发一个 issue 的行为…… 还有这个神奇的逻辑：你这个项目真不错，再帮我加上xxx就更完美了……

**Comment by DIYgod** [comment]
This people has been blocked.
