### ISSUE TITLE
Danmaku aways tell me she is loading- -！

### ISSUE THREAD

**Issue by zytx121** [DIYgod/DPlayer#106]
when i  import DPlayer into my vue website like  this:

![image](https://user-images.githubusercontent.com/10410257/28573059-dbe5e1c2-717b-11e7-8cd2-a8857e7600c4.png)

```
danmaku: {
  id: 'zy00000001',
  api: 'https://api.prprpr.me/dplayer/',
  addition: ['https://api.prprpr.me/dplayer/bilibili?aid=4045652']
}
```
doc say :
danmaku id, NOTICE: it must be unique, can not use these in your new player: `https://api.prprpr.me/dplayer/list`

i think it means when I need a new video danmaku, I need fill an unique id in it，also i need fill in danmaku‘s url in addition . 

Is it right?  but when i  fll in the addition , **danmaku aways tell me she is loading- -！**

notice: the demo can show the danmaku rightly.

**Comment by zytx121** [comment]
I guess i know what's happen- -!   my own code have some bug, and  i have fixed it!!

BTW,the addition links to bilibili danmaku database, and the id links to DPlayer-backend  danmaku database.

**Comment by DIYgod** [comment]
That's right.

**Comment by zytx121** [comment]
can i  ask something others but very important for me ?

![image](https://user-images.githubusercontent.com/10410257/28582937-e35a47cc-7199-11e7-88de-5602e10b3995.png)

how can i set the issue template ?  i can't find anything in baidu ,and nobody help me ...

plz!!!

**Comment by DIYgod** [comment]
https://github.com/DIYgod/DPlayer/tree/master/.github

**Comment by zytx121** [comment]
thx  sooooo  much!
