### ISSUE TITLE
播放器暂停时有烦人的广告

### ISSUE THREAD

**Issue by Misaka0612** [DIYgod/DPlayer#1073]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

-   The steps to reproduce.
-   A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
-   Which versions of DPlayer, and which browser / OS are affected by this issue?

**Comment by kn007** [comment]
这跟这个项目有啥关系。。。
本身播放器并无这个功能。

**Comment by TaylorWolfX** [comment]
这是你的网络被劫持了

**Comment by a9236** [comment]
这个播放器没有这个功能
请检查源码
