### ISSUE TITLE
源码在配置的最新环境中编译出错

### ISSUE THREAD

**Issue by cqsn558** [DIYgod/DPlayer#1081]
node版本14.13.1
webpack版本5.1.3
webpack-cli版本4.0.0
npm版本6.14.8
出错信息如下图：
![dplayer](https://user-images.githubusercontent.com/39335744/96328093-f607fe80-1071-11eb-8ecb-2ae024a8cea3.png)

**Comment by kn007** [comment]
？
建议你用编译好的版本。

这错误都告诉你，你这参数不存在了。

**Comment by cqsn558** [comment]
因为自己改了一些样式和部分代码，以前编译是成功的，这几天电脑重装了系统，配置的编译环境都是用的最新的，编译出来就出问题了，那两个未知参数去除后也会出现错误，但不知道问题出在哪，百度了一下也没找到答案。下图就是删除那两个参数后的错误提示：
![dplayer](https://user-images.githubusercontent.com/39335744/96329861-4d629a80-1083-11eb-89e8-143e8f97ebc0.png)

**Comment by cqsn558** [comment]
原来是webpack版本高了，降到4.40.2就可以正常编译了。

**Comment by kisexu** [comment]
兄弟，我编译成功啦。一开始也是报错，后来把nodejs版本降级到15就好啦。祝你好运！
