### ISSUE TITLE
pc端播放m3u8格式的视频流，第一次进去可以自动播放，在播放页面再次刷新后无法自动播放，求解决方案，

### ISSUE THREAD

**Issue by awen123** [DIYgod/DPlayer#1130]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

-   The steps to reproduce.
-   A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
-   Which versions of DPlayer, and which browser / OS are affected by this issue?

**Comment by 1265578519** [comment]
来个测试页面

**Comment by miseli** [comment]
> 来个测试页面

你试试这个,不是m3u8,但是同样的个别时候无法自动播放,复现很困难,多刷新几次会出现这种情况.
http://www.kuaikan33.com/Animation/douluodaludiyijimianfeiguankan/0-127.html

**Comment by mq1355066061** [comment]
确实存在，谷歌的话音量设为0就行了，应该是谷歌浏览器策略，火狐在设置后有音量也没问题。
