### ISSUE TITLE
使用dp.seek() 方法，无法跳转指定位置，自动跳回到视频0秒开始播放。

### ISSUE THREAD

**Issue by uddsoft** [DIYgod/DPlayer#1142]
使用dp.seek() 方法，如dp.seek(10),无法跳转指定位置，自动跳回到视频0秒开始播放。

**Comment by dengyang1993** [comment]
DPlayer.min.js   把他换成官方最新的,引入danmaku.js,不行的话尝试在引入其他的

**Comment by gnr2009** [comment]
playing 中实现seek 就可以解决ios端问题

**Comment by codehzy** [comment]
player难道不是视频播放一直会触发吗

**Comment by codehzy** [comment]
playing难道不是视频播放一直会触发吗，怎么做seek呢
