### ISSUE TITLE
帮你找了两个错误，我自己修复了，下次记得带上

### ISSUE THREAD

**Issue by kaihuang666** [DIYgod/DPlayer#1146]
都是关于safari浏览器的
第一：safari弹幕闪烁的问题，是因为无法渲染css动画
----- 我的解决方案：
.dplayer-danmaku .dplayer-danmaku-right.dplayer-danmaku-move {
	-webkit-transform-style: preserve-3d;
	transform-style:preserve-3d;
	backface-visibility:hidden;
	-webkit-backface-visibility: hidden;
	transform: translate3d(-100vw, 0px, 0px) rotate(0.1deg) !important;
	-webkit-transform: translate3d(-100vw, 0px, 0px) rotate(0.1deg)
		!important;
	text-shadow: 1px 1px 1px black !important;
}
第二：切换hls视频时，video标签重复，旧的video没有删除，新的video没有current标示
-----我的解决方案：只在safair测试过
$("body").on('click','.dplayer-quality-item',function() {
		$(".dplayer-video-current").remove();
		$(".dplayer-video").addClass("dplayer-video-current");
})
其他：我自己添加调整弹幕位置、手机端滑动快进、快退、音量加减、画中画等功能，如果你有打算添加这些功能，
发邮件到kevinluokai@qq.com，我打包发给你

**Comment by kaihuang666** [comment]
dplayer做的很好，继续加油

**Comment by kaihuang666** [comment]
另外，切换错误的问题，只是偶尔出现，没仔细去找问题

**Comment by qsw-net** [comment]
手机端播放m3u8 加载2次是啥问题

**Comment by ayasa520** [comment]
这个应该用 pull request 吧

**Comment by h175h32** [comment]
播放m3u8文件的时候 电脑端能播放 手机端加载失败，这是为什么呢？
