### ISSUE TITLE
在安卓端 qq 浏览器（11.2.5.5502版本）最新版本，dplayer无法播放m3u8视频（ In the latest version of Android QQ browser (version 11.2.5.5502), dplayer cannot play m3u8 video）

### ISSUE THREAD

**Issue by only1zhuo** [DIYgod/DPlayer#1157]
在安卓端 qq 浏览器（11.2.5.5502版本）最新版本，dplayer无法播放m3u8视频
In the latest version of Android QQ browser (version 11.2.5.5502), dplayer cannot play m3u8 video

**Comment by BrotaOne** [comment]
这个问题有解决的办法吗？我也碰到了
chrome 和 safari 上是正常的

**Comment by moyongqing** [comment]
我也遇到了，再其它浏览器正常，在安卓浏览器有页面但没有声音，苹果微信浏览器直接加载失败
