### ISSUE TITLE
禁止拖动进度条，hotkey 设置为false不生效

### ISSUE THREAD

**Issue by zhangqinbao** [DIYgod/DPlayer#1183]
大家有没有遇到这情况，或者告知下怎么禁止拖动播放进度条！谢谢

**Comment by skyflyll** [comment]
参考了别人的写法，使用css 样式去禁止拖动
.dplayer-bar-wrap {
    pointer-events: none !important;
}

**Comment by skyflyll** [comment]
> 大家有没有遇到这情况，或者告知下怎么禁止拖动播放进度条！谢谢

参考了别人的写法，使用css 样式去禁止拖动
.dplayer-bar-wrap {
pointer-events: none !important;
}
