### ISSUE TITLE
flv直播流切换清晰度后，后台继续拉取数据

### ISSUE THREAD

**Issue by guyijie1211** [DIYgod/DPlayer#1189]
如图
![pic](https://user-images.githubusercontent.com/23636549/119453315-e2d8b200-bd69-11eb-9726-9ee27233df71.png)

``` javascript
let dp = new DPlayer({
                container: document.getElementById('dplayer'),
                autoplay: true, //自动播放
                live: true,
                danmaku: true,
                video: {
                  type: 'customFlv',
                  quality: this.quality,
                  defaultQuality: 0,
                  customType: {
                    customFlv: function (video, player) {
                      const flvPlayer = flvjs.createPlayer({
                        type: 'flv',
                        url: video.src,
                      });
                      flvPlayer.attachMediaElement(video);
                      flvPlayer.load();
                    },
                  },
                },
              });
```

**Comment by meatbuns82** [comment]
你好，请问这个问题你解决了吗？我也遇到了同样的问题，不知道怎么能取消拉取上一个视频的流？如果解决了能分享一下方法吗，谢谢

Hi,  Did you solve this problem? I also meeting same questions, can you share your method of solve? thanks

**Comment by meatbuns82** [comment]
> 如图
> ![pic](https://user-images.githubusercontent.com/23636549/119453315-e2d8b200-bd69-11eb-9726-9ee27233df71.png)
> 
> ```js
> let dp = new DPlayer({
>                 container: document.getElementById('dplayer'),
>                 autoplay: true, //自动播放
>                 live: true,
>                 danmaku: true,
>                 video: {
>                   type: 'customFlv',
>                   quality: this.quality,
>                   defaultQuality: 0,
>                   customType: {
>                     customFlv: function (video, player) {
>                       const flvPlayer = flvjs.createPlayer({
>                         type: 'flv',
>                         url: video.src,
>                       });
>                       flvPlayer.attachMediaElement(video);
>                       flvPlayer.load();
>                     },
>                   },
>                 },
>               });
> ```
你好，请问这个问题你解决了吗？我也遇到了同样的问题，不知道怎么能取消拉取上一个视频的流？如果解决了能分享一下方法吗，谢谢

Hi, Did you solve this problem? I also meeting same questions, can you share your method of solve? thanks

**Comment by guyijie1211** [comment]
我后来换了HLS格式的流并且使用了 [zhw2590582/ArtPlayer](https://github.com/zhw2590582/ArtPlayer)  还是有这个问题。解决方法是在切换清晰度或关闭播放器时，先将之前的hls流destory就行了，不知道flv这样是否也行。你可以参考一下这个 [commit](https://github.com/guyijie1211/MixLive-vue/commit/0d4dbbd0ea15c1dedfd7a12fe50670bf397db244)
