### ISSUE TITLE
Can error event throw error message?

### ISSUE THREAD

**Issue by 2ue** [DIYgod/DPlayer#1204]
Can error event throw error message?

in my case, error can't throw error message, is something wrong with me ?

``` javascript
this.player = new DPlayer({
  container: document.getElementById('video'),
  autoplay: true,
  theme: '#2a67ff',
  loop: false,
  lang: 'zh-cn',
  screenshot: true,
  hotkey: true,
  preload: 'auto',
  volume: 0.7,
  mutex: true,
  video: {
    url: url,
    type: 'auto',
  },
});
this.player.on('error', (error) => {
  console.log('error==>', error);
});
```

now i console the error, always return undefined.

is there some other way to get the error message？
I want to do different things according to the error message

**Comment by likui-developer** [comment]
same question

**Comment by DIYgod** [comment]
Done cb6408a943e48e7ec31b2239a0ae76b86f56c934
