### ISSUE TITLE
subtitle cannot be displayed when playing files with m3u8

### ISSUE THREAD

**Issue by duanyuanping** [DIYgod/DPlayer#1205]

**Comment by zkeq** [comment]
I think I meet the same problem, 
Do you finally found the solution?
When I use m3u8 ,  p tags can't properly load...

When I use the mp4, it work properly:
![2022-01-21_081831.png](https://s2.loli.net/2022/01/21/MLOiXbmsjQGxpqF.png)
But when I use m3u8, no subtitles:
![2022-01-21_081742.png](https://s2.loli.net/2022/01/21/JPwrNHd15ThRWEa.png)

**Comment by DIYgod** [comment]
Repeated with #1244
