### ISSUE TITLE
关于弹幕的api

### ISSUE THREAD

**Issue by leadsoft-ware** [DIYgod/DPlayer#1217]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

-   The steps to reproduce.
-   A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
-   Which versions of DPlayer, and which browser / OS are affected by this issue?

请问这个弹幕的api是什么格式的，我试过加载从b站直接爬下来的弹幕，但是它显示damuku load failed

官网上的demo更离谱，console里面显示`已拦截跨源请求：同源策略禁止读取位于 https://api.prprpr.me/dplayer/v3/?id=9E2E3368B56CDBB4 的远程资源。（原因：CORS 请求未能成功）。`，那官网上demo的弹幕是哪来的

**Comment by misaka10843** [comment]
官网demo似乎是json
https://s-sh-17-dplayercdn.oss.dogecdn.com/1678963.json

**Comment by leadsoft-ware** [comment]
草，已经解决好几个月了，忘记关issue了，那json每条弹幕的含义是什么呢？

**Comment by WhimsFate** [comment]
> 草，已经解决好几个月了，忘记关issue了，那json每条弹幕的含义是什么呢？
```js
[
    0, // 时间, 单位：s
    0|1|2, // 弹幕类型： rolling 0 top 1 bottom 2
    15024726, // 十进制颜色
    'username',
    'text'
]
```

**Comment by codehzy** [comment]
请问你是怎么解决弹幕api问题的
