### ISSUE TITLE
右键信息能去掉么?

### ISSUE THREAD

**Issue by MaoSource** [DIYgod/DPlayer#1234]
![image](https://user-images.githubusercontent.com/56857029/141749341-129e9230-5159-4e8b-9065-5e04c75349a5.png)
这个默认的可以去掉么？

**Comment by a9236** [comment]
Dplayer.min.js里可以改

**Comment by MaoSource** [comment]
> dplayer.min.js里可以改

我用npm安装的要怎么改？

**Comment by LUDA0831** [comment]
//全局
.dplayer-menu-show {
  display: none;
}
// scoped
.player ::v-deep .dplayer-menu-show {
  display: none;
}

**Comment by aizhimou** [comment]
> //全局 .dplayer-menu-show { display: none; } // scoped .player ::v-deep .dplayer-menu-show { display: none; }

感谢
