### ISSUE TITLE
这个项目还维护么

### ISSUE THREAD

**Issue by trry-github** [DIYgod/DPlayer#1238]
想用又不敢用

**Comment by yingshaoxo** [comment]
同问。。。

**Comment by lihanspace** [comment]
同问，有好多问题，要是不维护我就自己改了发布了

**Comment by Tenodec** [comment]
> 

字节开源的弹幕敢用吗，danmu.js。简单的弹幕生成不是困难的事，困难的是优化，不造成卡顿。以前b站开源的danmuku也闭源了，

**Comment by Out-Of-Rain** [comment]
同问 @DIYgod

**Comment by DIYgod** [comment]
Yes, I occasionally fix bugs
