### ISSUE TITLE
请教大佬，chrome不能显示字幕，但firefox可以正常显示字幕，这样该怎么解决？

### ISSUE THREAD

**Issue by gianyao** [DIYgod/DPlayer#1271]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

-   The steps to reproduce.
-   A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
-   Which versions of DPlayer, and which browser / OS are affected by this issue?

**Comment by codehzy** [comment]
i use in chrome。it‘s current show

**Comment by DIYgod** [comment]
Unable to reproduce, please provide the minimum reproduction demo
