### ISSUE TITLE
在swiper中使用时，进度条无法使用

### ISSUE THREAD

**Issue by ZhangWei12138** [DIYgod/DPlayer#1283]
复现地址: https://codesandbox.io/s/swiper-default-vue-forked-rqv8j8?file=/src/App.vue

进度条无法点击滑动，并且点击时有概率会触发swiper的slide事件滑到下一页

**Comment by ZhangWei12138** [comment]
已解决 设置 no-swiping-class="dplayer-bar-wrap"

**Comment by super-auv** [comment]
设置完这个属性后, swiper不触发滑动了, 但是视频进度条也没法拖动了, 您这样也会吗?
