### ISSUE TITLE
为什么用hls 播放 m3u8格式的视频无法自动播放呢，是用法不对吗

### ISSUE THREAD

**Issue by jamesyao233** [DIYgod/DPlayer#1285]
![image](https://user-images.githubusercontent.com/30586884/180354538-c57c8230-b6e0-4bc6-b8dc-419a5737a116.png)

**Comment by jgckM** [comment]
这个可能会帮助到你 [Dplayer的基本使用](https://www.bilibili.com/video/BV11t41127K3/)
