### ISSUE TITLE
本地调试时，遇到了个跨域的问题，作为前端小白不知道如何去解决

### ISSUE THREAD

**Issue by jamesyao233** [DIYgod/DPlayer#1286]
这个是写的初始化播放的代码
`let video = new DPlayer({
          container: document.getElementById("videoPlayer"),
          video: {
            url: 'https://oss-test.kemiketang.com/meu8/teachResource/1/4.5.身体的“联络员”.m3u8',
            type: 'customHls',
            customType: {
              customHls: function (video: HTMLMediaElement, player: any) {
                const hls = new Hls();
                hls.loadSource(video.src);
                hls.attachMedia(video);
              },}
        }})`

**Comment by tangwanqi1991** [comment]
你的视频地址是无法播放的，先合合保证视频地址在浏览器上能正常播放。

**Comment by tangwanqi1991** [comment]
> 你的视频地址是无法播放的，先保证视频地址在浏览器上能正常播放。

**Comment by jamesyao233** [comment]
这个是m3u8的，直接播放肯定不行的吧，支持流播放的工具都是可以播放的 @tangwanqi1991

**Comment by tangwanqi1991** [comment]
那你写一个流的方法就可以了
