### ISSUE TITLE
如何将video.url动态赋值

### ISSUE THREAD

**Issue by akwangl** [DIYgod/DPlayer#1289]
比如视频资源是存在不同地方的，需要我发请求去从后台分别获取再赋值

**Comment by tangwanqi1991** [comment]
mount() {
    this.dp = new DPlayer({
    container: document.getElementById('dplayer'),
    video: {url:'', pic:''},
    subtitle:{
    url: '',
    type: 'webvtt' ,
    fontSize: '20px',
    底部: '5%',
    颜色: '#ffffff',
    }
    })
},

methods:{
   // 设置视频播放路径
    setVideoUrl (e) {
	    this.dp.switchVideo({url: e})
    },
}

**Comment by akwangl** [comment]
数据加载之前能不能有一个事件回调？我想自己去获取视频流数据，每个视频流的数据不是在一个url地址里面，这个代码好像只是切换不同视频资源，我的视频资源是用m3u8切片，有一小部分的数据不在同一个url地址

**Comment by tangwanqi1991** [comment]
这个需要你自己去写个方法，赋值就可以了

**Comment by akwangl** [comment]
好的，我稍后试一下

**Comment by tangwanqi1991** [comment]
动态获取字幕subtitle.url这个你有处理过吗？看了一遍文档，好像没有发现动态赋值的。只能写死喽

**Comment by akwangl** [comment]
我能确认一下吗？的确没有动态加载这一说吗？

**Comment by tangwanqi1991** [comment]
是的，我看过了api文档了，没有动态加载subtitle.url这一个API

**Comment by akwangl** [comment]
好的，我只能找找其他的视频处理框架了

**Comment by tangwanqi1991** [comment]
已经处理OK了。有兴趣可以加个微信twq18722859054

**Comment by akwangl** [comment]
好的
