### ISSUE TITLE
网页多人同步观影

### ISSUE THREAD

**Issue by JzeroM** [DIYgod/DPlayer#1295]
哈哈！简单套用了你的播放器实现异地观影
https://github.com/JzeroM/FantacyPlayer

**Comment by antnesswcm** [comment]
同步进度条哈哈，我一眼就瞟到这

**Comment by antnesswcm** [comment]
> 请问这个新插件怎么用吖？

研究研究别人怎么写的，套用到自己的网站就好了

**Comment by JzeroM** [comment]
> 同步进度条哈哈，我一看就看见了

是哦，但是有bug,在加载m3u8格式时候，电脑端基本没问题，就是手机端浏览器中途加入观影，影片会跳转到起始位置，但是MP4格式又没问题
