### ISSUE TITLE
Can't find HIs

### ISSUE THREAD

**Issue by duzhenyi** [DIYgod/DPlayer#1304]
![image](https://user-images.githubusercontent.com/45708243/189035581-b46bf83e-29aa-439b-8cfc-bebde68ecaac.png)
	 const dp =	new DPlayer({
				container: document.getElementById('dplayer'),
				preload: 'none',
				live: true,
				video: {
					url: 'http://192.168.0.114:8085/hls/aa01.m3u8',
					type: 'hls'
				}
			});

**Comment by cn-shenchao** [comment]
https://github.com/DIYgod/DPlayer/issues/1143#issuecomment-886325234

Hls存在window才有用，希望对你有帮助
