### ISSUE TITLE
安装最新版1.27.0 ，在拖动音量和鼠标点击定位播放位置的时候，左侧浮动的提示有些问题

### ISSUE THREAD

**Issue by lovleo** [DIYgod/DPlayer#1305]
安装最新版1.27.0 ，在拖动音量和鼠标点击定位播放位置的时候，有点左侧浮动的提示有些问题

If you want to report a bug, please provide the following information:

-   The steps to reproduce.
-   A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
-   Which versions of DPlayer, and which browser / OS are affected by this issue?

**Comment by enjoygayhub** [comment]
是左下侧notice不消失

**Comment by tampermonkeyStorage** [comment]
最新版1.27.0 ，https://github.com/DIYgod/DPlayer/blob/master/src/js/player.js#L595
切换清晰度后notice不消失

**Comment by 602376307** [comment]
请问拖动音量条或者用键盘改变音量时，左侧音量改变提示太频繁，如何解决

**Comment by DIYgod** [comment]
Fixed in 46722004d63c5ceeda7f17c9c770773b3c51e29a 255bbac7a4e0b423e91eb6c07aca146523bf61a6
