### ISSUE TITLE
请问怎么设置禁止迅雷下载 How to ban Thunder Download

### ISSUE THREAD

**Issue by a807966224** [DIYgod/DPlayer#1306]
我在使用dplayer的过程中，发现迅雷软件可以在当前网页页面下载视频，请问该如何禁止用户对视频的下载呢？原issus（https://github.com/DIYgod/DPlayer/issues/691）回复的内容对我没有帮忙，辛苦在重新帮忙解答下
In the process of using dplayer, I found that Thunder software can download videos on the current web page. How can I prevent users from downloading videos?

**Comment by DIYgod** [comment]
No way
