### ISSUE TITLE
1.27版切换清晰度左下侧提示不能自动消除

### ISSUE THREAD

**Issue by cqsn558** [DIYgod/DPlayer#1308]
在1.27个版切换清晰度后，有“正在切换至X画质”和“已经切换至X画质”，但“正在切换至画质”这个提示会一直显示，不能自动消除。
![1](https://user-images.githubusercontent.com/39335744/196064301-2d544d29-9d1f-44c6-aca3-0f25a96e038e.jpg)

**Comment by ebony0319** [comment]
统一的bug

**Comment by DIYgod** [comment]
Fixed in 6e780e048d3a13c32d5c7c297dd622f45c678d9a
