### ISSUE TITLE
拖动音量条或者用键盘上下箭头改变音量时，左侧音量改变提示太频繁。When dragging the volume bar or using the up and down arrows on the keyboard to change the volume, the left volume changes too frequently.

### ISSUE THREAD

**Issue by 602376307** [DIYgod/DPlayer#1309]
拖动音量条或者用键盘上下箭头改变音量时，左侧音量改变提示太频繁，要改动的话好像只能动源码？
When dragging the volume bar or using the up and down arrows on the keyboard to change the volume, the left volume changes too frequently.

**Comment by 602376307** [comment]
https://dplayer.diygod.dev/网站示例就是这样。

**Comment by FunnyZ** [comment]
同问，是要对事件做处理吗？

**Comment by tankpanv** [comment]
这个有什么解决办法了吗。按照官网示例的demo 点击音量键会频繁出现提示，按照react 老版本好像没有这个问题

**Comment by zym0110** [comment]
![image](https://user-images.githubusercontent.com/48800373/207748762-20f139f4-72cd-454e-afc6-5b7e750c7b76.png)

**Comment by jinyu2022** [comment]
这个明明1.26.0的版本就没这个问题。

**Comment by DIYgod** [comment]
Fixed in 46722004d63c5ceeda7f17c9c770773b3c51e29a
