### ISSUE TITLE
这是作者本人的爱发电吗？

### ISSUE THREAD

**Issue by izsiyy** [DIYgod/DPlayer#1323]
https://greasyfork.org/zh-CN/scripts/425955
这是上面这个脚本内含有的爱发电？请问是Dplayer的吗？

https://afdian.net/order/create?spm=aliyundrive.file_file_sharing.0.0.40a93575HNl03O&plan_id=be4f4d0a972811eda14a5254001e7c00

播放视频时候会弹出
![image](https://user-images.githubusercontent.com/87903717/218036475-e4340182-0781-4994-a7b7-22354dc44cd5.png)

**Comment by Burial0268** [comment]
这个很明显不是吧，readme.md里都提到了作者的爱发电了

**Comment by DIYgod** [comment]
不是，估计是脚本作者的
