### ISSUE TITLE
有没有遇到过Vue3使用的时候在pc的浏览器无法播放，黑屏呢

### ISSUE THREAD

**Issue by zouyu01-sz** [DIYgod/DPlayer#1331]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

-   The steps to reproduce.
-   A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
-   Which versions of DPlayer, and which browser / OS are affected by this issue?

**Comment by mmmmReed** [comment]
我也碰到了这个问题，请问你们解决了吗

**Comment by DIYgod** [comment]
Please add a minimal reproduction so we can investigate.

**Comment by yzebgdt** [comment]
草你妈的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月14日 01:36 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [DIYgod/DPlayer] 有没有遇到过Vue3使用的时候在pc的浏览器无法播放，黑屏呢 (Issue #1331) |

Closed #1331 as completed.
