### ISSUE TITLE
Jump m3u8 content cannot be played normally？

### ISSUE THREAD

**Issue by dysibai** [DIYgod/DPlayer#1349]
https://cdn.zoubuting.com/20210629/jaGXs022/index.m3u8

response: 

#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1200000,RESOLUTION=1280x720
/20210629/jaGXs022/1200kb/hls/index.m3u8

**Comment by DIYgod** [comment]
Please add a minimal reproduction so we can investigate.

**Comment by yzebgdt** [comment]
草你妈的



---- Replied Message ----
| From | ***@***.***> |
| Date | 08/14/2023 01:36 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | Re: [DIYgod/DPlayer] Jump m3u8 content cannot be played normally？ (Issue #1349) |

Please add a minimal reproduction so we can investigate.
