### ISSUE TITLE
Some videos can be played and some cannot be played, and there are no errors show in the chrome console and IDE console (springboot)

### ISSUE THREAD

**Issue by 98549844** [DIYgod/DPlayer#1352]
i using Dplayer 1.27.0 and upload to video, one video play success and one fail,
i using springboot 3 and thymeleaf to implement and 
there are no errors show in the chrome console and IDE console (springboot)

attached fail to play video and success play video for your reference

https://github.com/DIYgod/DPlayer/assets/26402108/e164612e-0d5e-4df6-947f-61963876a0ab

**Comment by DIYgod** [comment]
Please add a minimal reproduction so we can investigate.
