### ISSUE TITLE
Sync danmaku when seeking

### ISSUE THREAD

**Issue by soruly** [DIYgod/DPlayer#14]
I think the player should re-sync danmaku when seeking?

**Comment by DIYgod** [comment]
不太懂 re-sync 的意思，重新获取弹幕？

**Comment by soruly** [comment]
在時間軸跳到某個時間後，清除先前的彈幕?

**Comment by DIYgod** [comment]
这个没必要吧，我看那些弹幕网站用的播放器也没有做清除

**Comment by soruly** [comment]
喔 好的謝謝你 ;)
