### ISSUE TITLE
Unfluent in Firefox

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/DPlayer#21]

**Comment by dixyes** [comment]
As a matter of fact, DPlayer (include video and danmaku) ***is*** fluent at firefox, but firefox got stuck,
and if u use Chrome, DPlayer is not fluent, but the browser remain respondable (tested on the same test page: [my hexo test page](//dixyes.github.io)

**Comment by DIYgod** [comment]
I think it is caused by browser's bad optimize.
