### ISSUE TITLE
弹幕的问题

### ISSUE THREAD

**Issue by stevennight** [DIYgod/DPlayer#23]
可以导入B站或者说XML的弹幕么，或者转换储存。
因为想在校园内网使用，这样的需求稍微比弹射弹幕要大。

**Comment by Myer921** [comment]
@stevennight 貌似py版的dplayer弹幕后端可以导入b站弹幕
https://github.com/dixyes/dplayer_py_backend

**Comment by dixyes** [comment]
一大早被新生培训啥的吵醒
我顺手写了个convert.py json xml互转
gist ==> [covert.py](https://gist.github.com/dixyes/7be49ca8ae288f453469c1a309f8d3ed)

**Comment by stevennight** [comment]
@dixyes 
能不能详解一下这段
  "color":("#"+hex(int(danmaku[3])+0xff000000)[4:])[:7],
不懂python。颜色代码的转换不是很懂。

**Comment by dixyes** [comment]
danmaku[3]是十进制颜色吧，int(danmaku[3])可能在范围0x0到0xffffff内，直接hex（）转换会长度不一，所以加上0xff000000掩下高位，这样范围就固定了：0xff000000到0xffffffff再用字符串截取[4:]取索引是4以后的
最后那个[:7]是hex函数会输出0xff123333L这样的格式，把最后的L截取掉就转换成#颜色了

以上这个方法完全是晚上十二点以后拍脑子就想出来了的，肯定有更好的方法，但是毕竟
Now is better then never么，等有空了再考虑换个更高效稳定的方法，这个方法先用着
（同时挖了一大堆史诗级巨坑的我

**Comment by DIYgod** [comment]
Done. https://www.anotherhome.net/2790
