### ISSUE TITLE
希望提供一个修改弹幕 apiurl 的方法

### ISSUE THREAD

**Issue by RicterZ** [DIYgod/DPlayer#24]
在无刷新切换视频的时候，无法更新弹幕..
看了一下并没有提供修改 apiurl 重新载入弹幕的方法

**Comment by RicterZ** [comment]
重新跑一下 constructor 函数的话，会丢一部分弹幕或者干脆不显示

**Comment by dixyes** [comment]
以我多年经验，作者在沉迷屁股，建议你先试试删了整个div再新建一下？ 比起改整个dplayer要简单些?

**Comment by RicterZ** [comment]
我试试（

dixyes <notifications@github.com>于2016年9月16日周五 下午7:34写道：

**Comment by RexSkz** [comment]
It seems that your issue is duplicated with [this one](https://github.com/DIYgod/DPlayer/issues/11)...

**Comment by RicterZ** [comment]
@RexSkz 其实不一样来着..（

**Comment by RexSkz** [comment]
@RicterZ Alright, I think swithing video means swithing a lot of config items, such as:

```javascript
dp.switchVideoOption({
    video: {
        url: '若能绽放光芒.mp4',
        pic: '若能绽放光芒.png'
    },
    danmaku: {
        id: '9E2E3368B56CDBB4',
        api: 'https://dplayer.daoapp.io/',
        token: 'tokendemo',
        maximum: 1000
    }
});
```

**Comment by DIYgod** [comment]
为什么要重新载入弹幕，做什么用的？

**Comment by RicterZ** [comment]
就是重新载入视频
Wenjie Fan <notifications@github.com>于2016年9月19日 周一下午6:32写道：

**Comment by RicterZ** [comment]
是这样，重新载入视频的时候弹幕的key也更新了，但是修改视频地址的时候并不能同时修改弹幕的key

**Comment by DIYgod** [comment]
我添加了一个新API：`dp.switchVideo(video, danmaku)`，用来切换视频和弹幕，能否解决需求？

See: https://github.com/DIYgod/DPlayer/commit/cc45df71bc2964ba76606699fbe489aa12e26d70

**Comment by RicterZ** [comment]
👍
