### ISSUE TITLE
父元素设置了宽高无法全屏

### ISSUE THREAD

**Issue by shuyabin** [DIYgod/DPlayer#29]
父元素设置了宽高之后 全屏 也只能是 父元素的宽高..怎么破

**Comment by DIYgod** [comment]
```
.dplayer:-webkit-full-screen {
    height: auto;
    width: auto;
}
```

**Comment by shuyabin** [comment]
![image](https://cloud.githubusercontent.com/assets/14884581/19217448/f30b7f8a-8e0d-11e6-96fc-d5651ed29c3b.png) 
![image](https://cloud.githubusercontent.com/assets/14884581/19217452/04eab068-8e0e-11e6-915d-d044340c0236.png)   

貌似没用...

**Comment by DIYgod** [comment]
改成这样就可以了：
```
.dplayer:-webkit-full-screen {
    height: 100% !important;
    width: 100% !important;
}
```

话说为什么要设置宽高

**Comment by shuyabin** [comment]
因为 视频像素低 的时候 video的宽高会随着 视频的大小适应， 但是 外面的盒子 宽高是限定的所以会看不到 导航条

**Comment by shuyabin** [comment]
可以了！谢了。
