### ISSUE TITLE
Example when using as a module?

### ISSUE THREAD

**Issue by jeremyrajan** [DIYgod/DPlayer#3]
Great repo! Thank you...

Wanted to check, how one could include the player when exporting as a module? I am trying to use it in electronjs.

Any suggestions, would be great!

Cheers..

**Comment by DIYgod** [comment]
DPlayer is currently under development and should not be used in production.

## Work with module bundler:
In terminal:
```
$ npm install dplayer --save
```
In js:
```js
var DPlayer = require('DPlayer');
var dp = new DPlayer({
    // ...
});
```

Also, `DPlayer.min.css` should be referenced.

Cheers.

**Comment by jeremyrajan** [comment]
Thank you! 👍  appreciate it. Definitely understand, would love to contribute to the repo if interested :)

I tried this:  

```
const DPlayer = require('DPlayer');
let player = new DPlayer({
		element: $(elem),
		autoplay: false,
		theme: '#FADFA3',
		video: {
			url: 'http://o6m1pq7od.bkt.clouddn.com/最后的告白.mp4',
			pic: 'http://o6m1pq7od.bkt.clouddn.com/poster.jpg'
		}
	});
	player.init();
```

Comes back with `DPlayer is not a constructor`. Any idea?

Cheers!

**Comment by DIYgod** [comment]
```js
const DPlayer = require('DPlayer');
console.log(DPlayer);
```

To see what is being logged.

**Comment by jeremyrajan** [comment]
It returns as empty object `{}`

**Comment by DIYgod** [comment]
Sorry, I forget update npm package.

Updating DPlayer npm package to 0.0.2 version can fix this.

**Comment by jeremyrajan** [comment]
Awesome! it does fix the issue. :) Thank you...

There is another one tho (sorry about that). `Uncaught TypeError: this.element.getElementsByClassName is not a function`

I will raise up another issue tracker on this.

Cheers
