### ISSUE TITLE
rtmp直播流怎么接收

### ISSUE THREAD

**Issue by shuyabin** [DIYgod/DPlayer#32]
rmtp直播流怎么接收

**Comment by RexSkz** [comment]
似乎不行吧，目前还没有用 HTML5 直接解析 rtmp 的案例。

**Comment by shuyabin** [comment]
hhhh,看到 video++ 可以.

**Comment by RexSkz** [comment]
http://videojj.com/docs/#c_flash_md

看了一下，video++ 用的是 flash，不是 HTML5。

**Comment by liwanglin12** [comment]
@shuyabin @DIYgod 快抄袭-抄袭创新-创新-超越去

**Comment by shuyabin** [comment]
@liwanglin12  大神加油,就靠你了.

**Comment by dixyes** [comment]
举手 rmtp是啥 rtmp么

**Comment by shuyabin** [comment]
一时手抖,打错了. rtmp

**Comment by DIYgod** [comment]
没有找到解决方案，暂时无法实现
