### ISSUE TITLE
How to use video page index arg?

### ISSUE THREAD

**Issue by kmvan** [DIYgod/DPlayer#34]
e.g, http://www.bilibili.com/video/av698739/index_25.html 
this URL, page is 25, I can not find the page arg when to set.

**Comment by DIYgod** [comment]
可以使用cid获取

**Comment by BlueCocoa** [comment]
如果是用的WordPress的话，现在这边已经滋兹自动识别了
[DPlayer-WordPress v1.1.4](https://github.com/BlueCocoa/DPlayer-WordPress/releases/tag/v1.1.4) @kmvan

**Comment by DIYgod** [comment]
新计划：利用 http://www.bilibili.com/widget/getPageList?aid=1300989 这个接口获取

**Comment by DIYgod** [comment]
忘记更新了，可以这样获取：https://api.prprpr.me/dplayer/video/bilibili?cid=1024972
