### ISSUE TITLE
[建议]请问能新增切换视频源地址\切换清晰度的按钮功能吗？

### ISSUE THREAD

**Issue by CheapLolicon** [DIYgod/DPlayer#38]
一个视频源地址可能对某些用户缓存方面不太友好，因此想希望能有个按钮来切换视频源地址……
而且这样也可以弄个切换超清、高清、流畅的清晰度方面功能……
希望作者能新增这样的按钮功能

**Comment by Myer921** [comment]
@CheapLolicon 借用diygod一句原话
这只是一个播放器

**Comment by dixyes** [comment]
事实上吧  现在这个播放器已经变得越来越不simple stupid了
（或许我们应该fork出去一个分支 叫比如naive分支 然后把啥你们有需求的功能都加进去 然后把这边的master全部附加的功能全移除 大家就可以各取所爱了

**Comment by xtlsoft** [comment]
我觉得，现在不需要这种清晰度，你完全能自己把右键改一下，写道后端里面去。

**Comment by KiritoMiao** [comment]
同样需要（去魔改wp插件去）

**Comment by nba4488** [comment]
你好，我们真的很希望可以网站和网页还有网址解析所有全部视频网站里面的VIP会员 用券 付费 免费完整版视频画面质量清晰度1080P和4K还有原画下载下来观看就好了

**Comment by DIYgod** [comment]
Done. https://github.com/DIYgod/DPlayer/commit/83d795d983bf9a749fd0011eff042e2f56f86a24
