### ISSUE TITLE
视频返回是checksum error 是我参数没有喂够吗？

### ISSUE THREAD

**Issue by alexykuan** [DIYgod/DPlayer#45]

**Comment by journey-ad** [comment]
这个接口貌似不能指定otype为json，去掉试试

**Comment by alexykuan** [comment]
@journey-ad 两个接口都试了，都是checksum error

**Comment by journey-ad** [comment]
@alexykuan 签名里的参数和请求要一致，还是不行的话可能是你的签名生成方式有误。

**Comment by alexykuan** [comment]
@journey-ad 恩恩，确实参数喂错了，有的是参数是flv有的是mp4都要试着用。话说你还不睡吗 =。=

**Comment by journey-ad** [comment]
@alexykuan 一般在两点钟之后睡觉😪
