### ISSUE TITLE
Live streaming issue

### ISSUE THREAD

**Issue by soso851213** [DIYgod/DPlayer#49]
不好意思，想請教一下，我自己使用OBS(Open Broadcaster Software) 傳出來m3u8的live streaming，不能播放，但是我從twitch抓別人的的m3u8的live streaming能播放，是m3u8少設定了什麼嗎?  謝謝。

**Comment by dixyes** [comment]
但是这可能是hls.js的问题？
你可以试试单独用[hls.js的demo](http://dailymotion.github.io/hls.js/demo/)来测试下

**Comment by soso851213** [comment]
cannot Load http://127.0.0.1/hls/my.m3u8
HTTP response code:0 
this might be a CORS issue, consider installing Allow-Control-Allow-Origin Chrome Extension,network error

出現這個錯問訊息

**Comment by DIYgod** [comment]
http://bfy.tw/ATlA

**Comment by DIYgod** [comment]
跨域问题，加上 Allow-Control-Allow-Origin 头或者放到同一个域可解

**Comment by dixyes** [comment]
@DIYgod 
但是大佬 你确信原使用环境不是在127.0.0.1？
有没有可能只是这个hls的demo没弄好跨域

**Comment by soso851213** [comment]
已經解決了，原因是nginx上的nginx.conf沒有設定 Allow-Control-Allow-Origin，設定上去就OK了，感謝大家幫忙。
location /hls {  
# Disable cache
add_header 'Cache-Control' 'no-cache';

 # CORS setup
add_header 'Access-Control-Allow-Origin' '*' always;
add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
add_header 'Access-Control-Allow-Headers' 'Range';

# allow CORS preflight requests
if ($request_method = 'OPTIONS') {
add_header 'Access-Control-Allow-Origin' '*';
add_header 'Access-Control-Allow-Headers' 'Range';
add_header 'Access-Control-Max-Age' 1728000;
add_header 'Content-Type' 'text/plain charset=UTF-8';
 add_header 'Content-Length' 0;
return 204;
}
#server hls fragments  
types{  
application/vnd.apple.mpegurl m3u8;  
video/mp2t ts;  
}  
alias temp/hls;  
expires -1;  
}
