### ISSUE TITLE
可否支持.json里面的M3U8文件解析

### ISSUE THREAD

**Issue by xiaocongjiang** [DIYgod/DPlayer#53]
目前A站的M3U8文件格式为json文件格式里面封装TS文件，可否让DP支持此类后缀文件名的格式。

**Comment by dixyes** [comment]
你可以试着自己parse一下（感觉上dplayer致力于做一个简单的简洁的播放器而非大而全的大型项目

**Comment by DIYgod** [comment]
You should parse it yourself, it is not DPlayer's work.
