### ISSUE TITLE
Can not support bilibili format video

### ISSUE THREAD

**Issue by JamyBob** [DIYgod/DPlayer#56]
Just found bilibili format video can not be resolved，What is the problem？

Thanks.

**Comment by dixyes** [comment]
avid and your environment please

**Comment by JamyBob** [comment]
@dixyes 
This should not be related to the environment, the official Demo did not play successfully

Visit: http://dplayer.js.org/
Look at the second video

**Comment by DIYgod** [comment]
It works here, what happend?

**Comment by DIYgod** [comment]
It seems caused by cache, I'll fix it.

**Comment by JamyBob** [comment]
@DIYgod Thanks!

**Comment by DIYgod** [comment]
Fixed. https://github.com/DIYgod/DPlayer/commit/09aa61efe2044e258c3c03fbc65e73c55d33c6ef

**Comment by DIYgod** [comment]
@JamyBob Still can't work? Did you clear your browser cache?

**Comment by JamyBob** [comment]
@DIYgod
My fault, the problem is fixed, 

I have a question,
Why the latest npm version does not contain these changes?
