### ISSUE TITLE
double click the 弹幕 button,it will show something funny~~(layout error)

### ISSUE THREAD

**Issue by Studying-Man** [DIYgod/DPlayer#58]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

双击弹幕按钮，出现布局错乱。。

- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- Which versions of DPlayer, and which browser / OS are affected by this issue?

**Comment by DIYgod** [comment]
Fixed. https://github.com/DIYgod/DPlayer/commit/d65e0a349afb152f342c6b92b26edd1620d07a1e

Thank @guokeke .
