### ISSUE TITLE
导入B站弹幕

### ISSUE THREAD

**Issue by izuolan** [DIYgod/DPlayer#6]
支持导入B站的弹幕吗？

**Comment by DIYgod** [comment]
就像APlayer直接播放网易云音乐：[163music-APlayer-you-get-docker](https://github.com/YUX-IO/163music-APlayer-you-get-docker)，希望这种事是由第三方来做的，这个项目只是一个纯粹的播放器。

**Comment by izuolan** [comment]
我不会做，笑。所以问下。

**Comment by DIYgod** [comment]
后续应该会有人做的吧
