### ISSUE TITLE
請問一個播放Live m3u8 的問題

### ISSUE THREAD

**Issue by soso851213** [DIYgod/DPlayer#61]
問題是這樣的，假如現在沒Live源，DPlayer會找不到m3u8的檔案則無法播放，假如現在開始Live，觀看者必須重載頁面才能播放Live，請問DPlayer要怎麼不重整頁面，自動播放Live源，謝謝。

**Comment by dixyes** [comment]
搞个ws 然后直播开始时通过ws发消息
页面上搞个ws客户端 接收到开始信号就加载dplayer或者（机智如我

或者你就setint循环检查dplayer好了么 没有就刷新dplayer（更加机智

**Comment by soso851213** [comment]
謝謝你，我用你建議的第二種方法。
