### ISSUE TITLE
发现在ios自带浏览器safari中观看视频依然自动息屏的问题

### ISSUE THREAD

**Issue by YohoYang** [DIYgod/DPlayer#62]
ios10.3.1系统，浏览器ua信息为Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.0 Mobile/14E304 Safari/602.1
在使用safari观看dplayer的视频时，到达息屏时间依然会自动息屏，全屏后依然有这个问题，不知道是不是可以尝试解决这个问题，谢谢。

**Comment by DIYgod** [comment]
It's iOS System setting, I can't solve it.
