### ISSUE TITLE
请问对于优酷土豆等视频站点解析出来为mp4的切片文件DP怎么连播？

### ISSUE THREAD

**Issue by xiaocongjiang** [DIYgod/DPlayer#63]
如题。。。。
请问有何方法能使解析出来的多个切片地址自动实现无缝播放。

**Comment by haocity** [comment]
视频站点的ACCESS-CONTROL-ALLOW-ORIGIN. 是个问题

**Comment by liwanglin12** [comment]
@haocity 反代，没别的办法

**Comment by liwanglin12** [comment]
@haocity 要不你想办法找个全浏览器通用的bug绕过那个ACCESS LIMIT

**Comment by haocity** [comment]
@liwanglin12 曲线救国 要是mp4的话可以叠video标签 然后根据播放时间显示出来   不过我测试的是控制video标签的显示和隐藏会有一部分延迟(画面一闪)

**Comment by liwanglin12** [comment]
@haocity 我在回复另一个人。。（

**Comment by A-Circle-Zhang** [comment]
我也想解决这个问题呢。

**Comment by DIYgod** [comment]
Done. https://github.com/DIYgod/DPlayer/commit/a042b39550f4fd2e415dde3d249dcd45dd3d8236

Usage: http://dplayer.js.org/docs/#/?id=segmented-videos-support-unstable

Notice that this function is unstable, **don't use it in production environment**.
