### ISSUE TITLE
How can I play every P is the video more than one P in Bilibili?

### ISSUE THREAD

**Issue by sppsun** [DIYgod/DPlayer#64]
Hi Sir, you really have done perfect work, but I want to know if the video more than one P, how can I play them? Thank you. @DIYgod

**Comment by RexSkz** [comment]
DPlayer is not a special player for full Bilibili support.

I think using `dp.switchVideo` method written in [DPlayer docs](http://dplayer.js.org/docs/#/?id=api) is a good way, for instance:

```javascript
// ES6
dp.on('ended', () => {
    alert(`We'll play the next part in 5 minute...`);
    setTimeout(() => {
        dp.switchVideo({
            // video settings for next part
        }, {
            // danmaku settings for next part
        });
    }, 5000);
});
```

**Comment by sppsun** [comment]
Thank you for your answer, but I have another question now, I want to store the danmaku some one sended in my own database, do you have any suggestions?

**Comment by RexSkz** [comment]
You can look for [Related Projects](https://github.com/DIYgod/DPlayer#related-projects), some of them are backends for specific languages or frameworks.

**Comment by sppsun** [comment]
OK， thank you very much! @RexSkz
