### ISSUE TITLE
请问手机全屏能让它自动横屏么

### ISSUE THREAD

**Issue by stevennight** [DIYgod/DPlayer#65]
试了下，内置html5播放器是可以的。请问可以也做到那样子吗。

**Comment by stevennight** [comment]
好了， 早知道先找一下再提交issue....

**Comment by chenbowu** [comment]
怎么解决的，能说下吗

**Comment by stevennight** [comment]
> 怎么解决的，能说下吗

使用了screen.orientation.lock('landscape'); 全屏的时候去横屏，因为某些原因，当时貌似动了dplayer的代码，所以直接是click全屏按钮之后进行了全屏并且执行横屏。另外，至于兼容性不是很清楚…
https://github.com/stevennight/Stevennight_Live/blob/2023e97f5471248ea7f31b7202ce2e9f9b2f21e0/resources/views/room.blade.php#L508   这代码还请别见笑。

搜了一下，不知道这种能不能实现全屏横屏，https://q.cnblogs.com/q/56878/

**Comment by stevennight** [comment]
> 怎么解决的，能说下吗

看了一下dplayer有个fullscreen的事件可以监听然后处理? 还没有测试过，刚刚留意到。
