### ISSUE TITLE
demo的第二个视频（Bilibili video）放到1分7秒就加载不了了

### ISSUE THREAD

**Issue by FrankHan** [DIYgod/DPlayer#67]
我是用ipad（ios10）观看的demo：http://dplayer.js.org
发现第二个视频（bilibili video）放到1分7秒就放不动了。（注意是从头开始放，不要用手拖动进度条）此时，必须手动把进度条向后拖动才能播放后面的视频。
用windows7的电脑的chrome浏览器看这个视频，同样的，播放到1分3秒左右加载就变得非常慢。
我自己用hexo搭建的博客也有这个问题。

**Comment by journey-ad** [comment]
bilibili方面的限制，加载10M左右后就会断流。

**Comment by FrankHan** [comment]
您好，感谢您的解答，那这个问题有办法解决吗？毕竟用DPlayer的主要目的就是播放bilibili视频和弹幕...

**Comment by KiritoMiao** [comment]
基本没救（传说中的1分7秒死亡

**Comment by KiritoMiao** [comment]
自己服务器分发大法好

**Comment by FrankHan** [comment]
好的，谢谢你哦！




发自网易邮箱大师
在2017年04月29日 16:53，Kirito 写道：

自己服务器分发大法好

**Comment by FrankHan** [comment]
@KiritoMiao  我请教个小问题，我用七牛云的对象存储，然后在hexo博客里加载七牛云存储的视频，感觉加载速度很慢：http://frankhan.net/20-test-video/#mp4可播放  （就是这个页面的第一个视频）

我看DPlayer作者的示例好像也是用的七牛云对象存储（ http://devtest.qiniudn.com/若能绽放光芒.mp4 ），为什么加载一点都不卡呢？

**Comment by liwanglin12** [comment]
@FrankHan I think is your network issue, this video performance is excellent on my PC.

**Comment by FrankHan** [comment]
@liwanglin12  OK. Thank you!

**Comment by fly3949** [comment]
clouddn.com 测试域名限速

**Comment by FrankHan** [comment]
@fly3949 嗯，我发现了。我刚才看了一下七牛云的文档，看到了这个：https://developer.qiniu.com/fusion/kb/1319/test-domain-access-restriction-rules

![360 16460602706465](https://cloud.githubusercontent.com/assets/3120844/25564357/714113c6-2de4-11e7-8427-c74430f77f68.jpg)

但是我没太明白，我只是需要对于一个文件加速，这个"融合CDN"是自己的域名加速，我不需要对于博客的域名加速啊，我只是想加载这个mp4的时候能快一点，不知道我的理解哪儿有问题吗？

**Comment by BlueCocoa** [comment]
@FrankHan 你需要的是文件存储，不是CDN

**Comment by FrankHan** [comment]
@BlueCocoa 我用的就是对象存储，首先是在对象存储里面说这个是测试链接，有网速限制：

![360 164003018713888](https://cloud.githubusercontent.com/assets/3120844/25564407/470638ba-2de5-11e7-9fc3-85197c596f86.jpg)

点上面箭头画出来的链接进去就是这个：

![2](https://cloud.githubusercontent.com/assets/3120844/25564406/47055be8-2de5-11e7-990f-53a2143efa29.jpg)

再点上面箭头画出来的链接进去就是这个（融合CDN）：

![3](https://cloud.githubusercontent.com/assets/3120844/25564408/470726d0-2de5-11e7-9375-a2f728eca05b.jpg)

难道我白充了十块钱!!!  >.<

**Comment by BlueCocoa** [comment]
有七牛托管的，在qnssl.com下的二级域名的融合CDN（范围是mainland China）

**Comment by FrankHan** [comment]
@BlueCocoa 好的，有空我再研究下，谢谢你的回答！

**Comment by RexSkz** [comment]
@BlueCocoa https://segmentfault.com/q/1010000008929489 According to this answer, Qiniu won't provide domain name like *.qnssl.com anymore.
