### ISSUE TITLE
提示找不到标签

### ISSUE THREAD

**Issue by lubaolei161** [DIYgod/DPlayer#69]
你好，
我的博客是hexo+next 搭建的，安装了插件之后，在文章中添加以下标签

{% dplayer "url=http://home.ustc.edu.cn/~mmmwhy/GEM.mp4"  "pic=http://home.ustc.edu.cn/~mmmwhy/GEM.jpg" "loop=yes" "theme=#FADFA3" "autoplay=false" "token=tokendemo" %}

本地运行测试后提示报错：
![1](http://opj0cbfmf.bkt.clouddn.com/1.jpg)

提示找不到dplayer标签，请问如何解决

**Comment by RexSkz** [comment]
You can show us what you have done to install DPlayer in your blog, it could be helpful.

According to [Issues of hexo-tag-dplayer](https://github.com/NextMoe/hexo-tag-dplayer/issues) , this error didn't occur before.

**Comment by dixyes** [comment]
i've seen this before:
that user installed hexo-tag-aplayer
:shrug:

**Comment by RexSkz** [comment]
@dixyes Found that issue. 23333 But that's not like this...

**Comment by dixyes** [comment]
我们应该让 @DIYgod 把俩player集成在一起的（

**Comment by RexSkz** [comment]
@dixyes What about KISS?

**Comment by dixyes** [comment]
@RexSkz simple and stupid like adplayer -- advertisement player
avaliable for any voice advertisement and video advertisement!
even picture!

**Comment by RexSkz** [comment]
@dixyes AdPlayer - 🍭 Wow, such a lovely HTML5 danmaku advertisement player 23333

**Comment by DIYgod** [comment]
@dixyes @RexSkz Great suggestion, I'll consider it.
