### ISSUE TITLE
当鼠标在进度条上的时候，希望能显示当前所指的时间

### ISSUE THREAD

**Issue by acalimit** [DIYgod/DPlayer#71]
![20170513221513](https://cloud.githubusercontent.com/assets/5378519/26026224/0af36f38-382a-11e7-90a2-9336e0ec823a.png)
类似这样子，跳转的时候方便点，不然有时候要点几次才能跳转到需要的时间点。

**Comment by DIYgod** [comment]
Done. https://github.com/DIYgod/DPlayer/commit/f6303d4903ea58c912128b74623d5ab399d5cf2a
