### ISSUE TITLE
怎么不让控制条出现

### ISSUE THREAD

**Issue by xianzhi0520** [DIYgod/DPlayer#72]
仅仅需要播放功能  也不需要声音 怎么让控制条不显示

**Comment by dixyes** [comment]
使用video标签而不是dplayer
参考 https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video

use video tag only instead of dplayer
see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video for more information

**Comment by liwanglin12** [comment]
@dixyes 双语的话把链接里en-US改成zh-CN怎么样

**Comment by dixyes** [comment]
好主意 @liwanglin12

**Comment by xianzhi0520** [comment]
@dixyes 没有办法  video无法满足我的需要  我需要这个播放器  又想做一个预览  声音可以控制 控制条应该 弄一个属性  也控制一下呗

**Comment by DIYgod** [comment]
Use custom CSS:

```
.dplayer-controller {
    display: none;
}
```
