### ISSUE TITLE
The seek method can be used normally in the page end, but it does not take effect in the mobile phone ios. The progress bar jumps to the position of seek when preloading, but the video starts to play from 0 after using paly(). What's the reason

### ISSUE THREAD

**Issue by KIMwofe** [DIYgod/DPlayer#771]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

-   The steps to reproduce.
-   A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
-   Which versions of DPlayer, and which browser / OS are affected by this issue?

**Comment by ChandlerBent** [comment]
I have same question.

How to resolve?

**Comment by mysteriousCL** [comment]
I have same question.

How to resolve?

**Comment by DIYgod** [comment]
Unable to reproduce, please provide the minimum reproduction demo
