### ISSUE TITLE
Release v1.2.0

### ISSUE THREAD

**Issue by egoist** [DIYgod/DPlayer#79]
The latest version is still `v1.1.4` on npm: https://unpkg.com/dplayer@latest/

**Comment by DIYgod** [comment]
Version 1.2.0 is not ready.🌝

**Comment by egoist** [comment]
But the doc reflects 1.2.0 usage 😂

**Comment by DIYgod** [comment]
There are some confusion🌝, I'll release v1.2.0 after finishing https://github.com/DIYgod/DPlayer/issues/63.

**Comment by DIYgod** [comment]
Release!
