### ISSUE TITLE
问下作者

### ISSUE THREAD

**Issue by bbaa-bbaa** [DIYgod/DPlayer#84]
弹幕返回的_id有什么特殊意义么？
如"593d4e42b3c438607d6cb8d7"
{"code": 1, "data": {"__v":0,"author":"DIYgod","time":0,"text":"test","color":"#fff","type":"right","ip":"*.*.*.*","referer":"http://127.0.0.1/test.html","_id":"593d4e42b3c438607d6cb8d7","player":["random"]}}

**Comment by dixyes** [comment]
这个弹幕对象的唯一标识符
（实际上没卵月

**Comment by DIYgod** [comment]
一些定制化需求可能会用到，不需要的话不用管就好了
