### ISSUE TITLE
The Player cannot Full the screen

### ISSUE THREAD

**Issue by Wj3344** [DIYgod/DPlayer#87]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- Which versions of DPlayer, and which browser / OS are affected by this issue?

**Comment by DIYgod** [comment]
Can you see issue template?

**Comment by dixyes** [comment]
@diygod
为了表达你的心情 我建议你使用Can't或者CANNOT而不是can
（滑稽

**Comment by DIYgod** [comment]
@dixyes 本来是想这么写的，但是忍住了

**Comment by dixyes** [comment]
@Wj3344 如果你想帮助开发者修复问题，而不（只）是想调戏作者（同样可以在issue机制中实现），
请提供必要的 使问题重新出现的条件
例如在win10/chrome下 某条件下点击某个地方出现了某种错误

以及@diygod 你那个模板对中文使用者确实不大友好

**Comment by Wj3344** [comment]
就是在看视频的时候没办法全屏，然后，这github上的英文又不怎么看得懂

![Uploading GEA~14WDWMTXQKWD{9Z8`40.png…]()

**Comment by journey-ad** [comment]
@Wj3344 你的截图没有被上传，看不懂英文可以使用翻译工具帮助理解。
提供一个**出现此问题的页面地址**和你的**操作系统版本**、**浏览器版本**以便排查问题。
