### ISSUE TITLE
switchVideo() have no effect in 1.3.0

### ISSUE THREAD

**Issue by YohoYang** [DIYgod/DPlayer#88]
I have use the earlier 1.2.0 version before releases, it work ok.
But since 1.2.0 releases and 1.3.0, the switchVideo() have no effect even on your demo.
I hope it will be fix.
 
AND, last time my issues of the ios safari will close screen is not a issues, if <video> roop is true, iPhone will close screen.

**Comment by YohoYang** [comment]
Yeap, the event dp.on("error",function(){}) seems like doesn't work too.

**Comment by kslr** [comment]
Please provide demo code.

**Comment by YohoYang** [comment]
Official demo is the best demo http://dplayer.js.org
when I Click the Switch video video replay but url never change.

And the error event:
var dp = new Dplayer(){...} 
dp.on("error",function(){
console.log("test")} )

when the url broken or other reason make the dplayer error, no log in console. I tried to changed "error" to "pause" it works ok.

**Comment by YohoYang** [comment]
And Quality Switch not work on Microsoft Edge.

**Comment by DIYgod** [comment]
Confirmed, I'll fix it.

**Comment by sinchang** [comment]
after click "switch video" on official demo, console error `_this.video.currentTime is not a function`

**Comment by DIYgod** [comment]
Done. Thank @sinchang .
