### ISSUE TITLE
Iphone wkwebview play video, and then shrink the page will appear card Dayton

### ISSUE THREAD

**Issue by JaneCC** [DIYgod/DPlayer#89]
Iphone wkwebview play video, and then shrink the page will appear card Dayton

**Comment by DIYgod** [comment]
I can not understand you.

**Comment by dixyes** [comment]
猜下蛤 Dayton是代顿 shrink是收缩
使用逐字翻译: iphone wkwebview 播放 视频，然后 缩小 页面 将会 出现 卡 代顿
so i guess, what he what to say is
when using WKWebView on iPhone, resizing this view will cause lagging
怕是国产渣翻译受害者
所以说为啥非要英文啊 中文不一样好么
d' u think ur user is major English speaker?
