### ISSUE TITLE
Latest release

### ISSUE THREAD

**Issue by Myer921** [DIYgod/DPlayer#9]
hexo插件填坑的不是我，所以不要写我名字
我主要是帮个忙提交罢了，同时也只是个使用者（挖坑）

你要谢这位帮忙填坑@dixyes

**Comment by Myer921** [comment]
搞ubuntu的本地开发环境真累 简直爆炸 不过今天应该尘归尘土归土了

**Comment by DIYgod** [comment]
你俩都加上啦，不管怎样都谢谢啦~~

**Comment by Myer921** [comment]
那我就close咯
