### ISSUE TITLE
Fullscreen in iframe

### ISSUE THREAD

**Issue by General110** [DIYgod/DPlayer#91]
<iframe height=320 width=100% src="http://dplayer.js.org/" allowscriptaccess="always"></iframe>

只是填充iframe标签没有真正全屏

**Comment by DIYgod** [comment]
You should add `allowfullscreen` attribution in iframe, like:

`<iframe height=320 width=100% src="http://dplayer.js.org/" allowscriptaccess="always" allowfullscreen></iframe>`
