### ISSUE TITLE
【建议功能】跨域iframe通讯，资源站 dplayer 被放在iframe，站长难以控制和获取播放状态

### ISSUE THREAD

**Issue by xiaoer3301** [DIYgod/DPlayer#919]
**主要问题**
资源站 dplayer 被放在iframe，站长难以控制和获取播放状态

**为什么被放在iframe**
资源站视频的m3u8个别经常出现不支持跨域访问，无奈只能使用资源站提供的iframe

**为什么不让站长实现**
难以沟通，资源站过多，实现无法统一。

**想要的效果**
通过 `window.postMessage` 跨域通讯达到此功能。
例如：
父页面向dplayer页面发送 `postMessage({type: 'play'})`：开始播放
父页面向dplayer页面发送 `postMessage({type: 'pause'})`：暂停播放
父页面向dplayer页面发送 `postMessage({type: 'play', time: 100})`：从100秒开始播放

dplayer 向父页面发送  `postMessage({type: 'play'})`：开始播放
dplayer 向父页面发送  `postMessage({type: 'pause'})`：暂停播放
dplayer 向父页面发送  `postMessage({type: 'error', data:'错误内容'})`：播放错误

联动通讯：
父页面向dplayer页面发送 `postMessage({type: 'getTime'})`：获取播放时间
    此时 dplayer 向父页面发送  `postMessage({type: 'getTime', time: 100})`：发送播放时间

**补充**
资源站视频经常出一些问题，因为是使用iframe（使用iframe是因为许多m3u8资源不支持跨域访问），而无法知晓资源是否已经失效、或者过于卡顿，通过postMessage还能操作播放状态。

但我们可以解决这个问题，通过通讯传递 postMessage，只要dplayer原生支持这个功能，就可以有更多的自由！
https://developer.mozilla.org/zh-CN/docs/Web/API/Window/postMessage

**通讯例子**
```html
<!-- 父页面 -->
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
<iframe id="iframe" src="http://0.0.0.0:1111/statics/iframe.html"></iframe>
<button onclick="postmessage()">传递到子窗口</button>
<script type="text/javascript">
window.addEventListener("message", function(e) {
  console.log(e.data)
}, false);
function postmessage() {
  let dom = document.getElementById('iframe')
  dom.contentWindow.postMessage('我是你爸爸', '*')
}
</script>
</body>
</html>
```

```html
<!-- 子页面 -->
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
<button onclick="postmessage()">传递到付窗口</button>
<script type="text/javascript">
function postmessage() {
  window.parent.postMessage('我是你儿子', '*')
}
window.addEventListener("message", function(e) {
  console.log(e.data)
}, false);
</script>
</body>
</html>
```

**Comment by aston314** [comment]
好像没有支持

**Comment by DIYgod** [comment]
This should be the job of the iframe page and not the player
