### ISSUE TITLE
There is a performance issue in pushDanmaku(), seriously

### ISSUE THREAD

**Issue by micooz** [DIYgod/DPlayer#92]
- Current Behaviour

FPS reduce to zero for a long time when a large amount of danmaku loaded at the beginning.

<img width="1021" alt="qq20170625-145743 2x" src="https://user-images.githubusercontent.com/8897063/27514337-2cf53cfe-59ba-11e7-9a6b-9da90ac1c6d8.png">

- The steps to reproduce.

Just start to play the first demo.

- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.

http://dplayer.js.org/

- Which versions of DPlayer, and which browser / OS are affected by this issue?

DPlayer: v1.3.1
Browser: Chrome 59.0.3071.109
OS: macOS Sierra 10.12.5

The problem is probably because [this.pushDanmaku] is called multiple times during a very short time.

This would not be a performance problem, but unfortunately, `this.pushDanmaku` does DOM operations(reflow and repaint both happened) which have a bad performance.

BTW, advises here:

1. Queue/throttle pushDanmaku() calls.
2. Make pushDanmaku() asynchronous.
3. [createDocumentFragment] would be helpful.

[this.pushDanmaku]: https://github.com/DIYgod/DPlayer/blob/master/src/DPlayer.js#L151-L159
[createDocumentFragment]: https://developer.mozilla.org/en-US/docs/Web/API/Document/createDocumentFragment

**Comment by DIYgod** [comment]
Done. https://github.com/DIYgod/DPlayer/commit/4d2c45948f7185f925a95e4fdda25cbd382e69c4
