### ISSUE TITLE
1.26 播放m3u8 倍速功能无效

### ISSUE THREAD

**Issue by hanximeng** [DIYgod/DPlayer#941]
版本：1.26
设备环境：Mobile
浏览器：Chrome / Via /Edge
故障描述：手机端播放m3u8选择倍速而视频并没有加速播放，已引入hls。

**Comment by k9sec** [comment]
解决了吗 我也是 手机谷歌浏览器 我使用video引用mp4 使用dom的playbackRate都可以设置，但是使用dplayer获取的dom这个属性却失效了。还望答疑

**Comment by k9sec** [comment]
版本：1.26
设备环境：Android 一加6、华为
浏览器：Chrome / Via /Edge
故障描述：手机端播放m3u8选择倍速而视频并没有加速播放，已引入hls。
在PC端上倍速是正常的，手机失效

**Comment by TestsLing** [comment]
有解决办法吗？我这边也出现了这个问题
